Add files via upload

diff --git a/src/comet b/src/comet
--- a/src/comet
+++ b/src/comet
@@ -4,12 +4,12 @@
 PIDcomet=$(grep Comet $LOC../install_locations | awk '{print $2}')
 
 if [ ! -f $PIDcomet ]; then
-	echo -e "\n Error " $PIDcomet " is not a file  \n" |tee -a "$datelog"
-	exit 1
+    echo -e "\n Error " $PIDcomet " is not a file  \n" | tee -a "$datelog"
+    exit 1
 fi
 
 # run comet 
-"$PIDcomet" -P"$PIDparam" "$PIDinput" |tee -a "$datelog"
+"$PIDcomet" -P"$PIDparam" "$PIDinput" | tee -a "$datelog"
 
 if [[ $COMEToutput == "" ]]; then
     COMEToutput=$(echo $STout*.xml)
